### ISSUE TITLE
VP and TT not harvesting latest extremo

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#11]
Please make sure by the end of the day the latest extreme I was in the right folder to be harvested automatically by our apps so people trying them will get the absolute latest extreme out without any effort thanks

**Comment by ghost** [comment]
Is that better?

**Comment by dberlow** [comment]
Yes, Though that’s not the last version of the day is long as it’s gotten this version gets the next version from the same place it should be OK

**Comment by ghost** [comment]
I haven't added an auto update (beyond the existing once-a-day update on typetools) but the Grab New Fonts link under META will grab them. I could add an hourly update for today if you like.
