### ISSUE TITLE
Copy url

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#12]
This is almost working, but not getting the font?

![7D8CBA55-0A64-41CF-9F6A-13FB37584F53](https://user-images.githubusercontent.com/1956494/62542734-68544080-b82a-11e9-8032-1a0ef81e12af.png)

Yields: https://videoproof.typenetwork.com/?font=custom-RobotoExtremo&mode=grid&glyph-group=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%3C(%5B%7B%40%23%24%25%26%3F!%2F%7C%5C%22~%60*%5E%27%3A%3B.%2C)%5D%7D%3E&foreground=%23000000&background=%23ffffff&timestamp=0

Showing:
![AB40628F-2631-4545-9D43-BD9AF76C55BF](https://user-images.githubusercontent.com/1956494/62542781-81f58800-b82a-11e9-94ec-91b5c90b406b.png)

**Comment by dberlow** [comment]
Will be supplying pdf proofs for extremo to replace the proofing requirements.

**Comment by ghost** [comment]
I suspect what happened there was you had uploaded a custom Extremo, which can't be communicated via the URL. (The "built in" Extremo that is available in the dropdown has a space in the name.)

**Comment by dberlow** [comment]
Thanks I’ll try that

**Comment by ghost** [comment]
This one works. https://videoproof.typenetwork.com/?font=RobotoExtremo-VF&mode=grid&glyph-group=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%3C(%5B%7B%40%23%24%25%26%3F!%2F%7C%5C%22~%60*%5E%27%3A%3B.%2C)%5D%7D%3E&foreground=%23000000&background=%23ffffff&timestamp=0

**Comment by dberlow** [comment]
For curiosity sake what kind of port would be required to make the same thing work n typetools?

On Aug 6, 2019, at 1:04 PM, Chris Lewis <notifications@github.com> wrote:

This one works. https://videoproof.typenetwork.com/?font=RobotoExtremo-VF&mode=grid&glyph-group=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%3C(%5B%7B%40%23%24%25%26%3F!%2F%7C%5C%22~%60*%5E%27%3A%3B.%2C)%5D%7D%3E&foreground=%23000000&background=%23ffffff&timestamp=0

**Comment by ghost** [comment]
Typetools just has loads of information that needs to be recorded, at least for the Ramp page: X number of controls times the five styles. But it could be done!

**Comment by dberlow** [comment]
Is it easier to add a typetools kind of layout to video proof, and then go from there to urls, or not?

On Aug 6, 2019, at 1:17 PM, Chris Lewis <notifications@github.com> wrote:

Typetools just has loads of information that needs to be recorded, at least for the Ramp page: X number of controls times the five styles. But it could be done!

**Comment by ghost** [comment]
I don't think one way is particularly easier than the other. Perhaps the larger question here is, do you have an idea of combining typetools and videoproof someday?

**Comment by dberlow** [comment]
As I propose in the slides, yes typetools ramp, becomes the ramp-defining tool in videoproof. Other layouts are absorbed accodingly?

**Comment by ghost** [comment]
Okay, will ponder that. Closing this one for now.

**Comment by dberlow** [comment]
Chris, 
This Ramp move to videoproof and expansion into portal space is shown on slide 2 of “runion box1” of that shared slideshow— To think about in yonder ponder. Thanks

On Aug 13, 2019, at 1:40 PM, Chris Lewis <notifications@github.com> wrote:

Okay, will ponder that. Closing this one for now.
