### ISSUE TITLE
Long delay on page load in Safari

### ISSUE THREAD

**Issue by ghost** [TypeNetwork/videoproof#13]
Something about the page is causing a long period of heavy CPU usage while the page loads in Safari. Doesn't happen in other browsers.

**Comment by ghost** [comment]
I'm stumped by this. Whatever it is completely crushes the Safari debugging panel, so it's hard to investigate. The page load timeline shows most of this time occupied by network access, which doesn't make sense with the symptom of maxing out the CPU.

**Comment by graphicore** [comment]
Can't reproduce anymore.
