### ISSUE TITLE
Old buggy Amstelvars in font menu

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#19]
The current Amstelvar Roman in the videoproof and  typetools font menus is buggy. 
Please please with:
https://github.com/TypeNetwork/Amstelvar/blob/master/fonts/Amstelvar-Roman-VF.
Thanks

**Comment by ghost** [comment]
Okay, I will add the Amstelvar-Roman-VF and Italic-VF from there and remove the ones currently listed. Do you also want anything from the AmstelvarAlpha repo, or is that retired?

**Comment by dberlow** [comment]
Dave wants to keep alpha.
We will also be calling everything in between Roboto classic and Roboto Extremo, probably next week.Thanks

On Oct 7, 2019, at 12:05 PM, Chris Lewis <notifications@github.com> wrote:

Okay, I will add the Amstelvar-Roman-VF and Italic-VF from there and remove the ones currently listed. Do you also want anything from the AmstelvarAlpha repo, or is that retired?

**Comment by ghost** [comment]
Done.
