### ISSUE TITLE
Show Github Link at bottom of left sidebar

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/videoproof#2]
As a user, when I visit https://videoproof.typenetwork.com, I expect to fine a link to the project's source Github Repo (https://github.com/TypeNetwork/videoproof) and a link to the issue tracker (https://github.com/TypeNetwork/videoproof/issues/) with a solicitation to file issue with bugs or feature ideas. 

This should be done in a similar way to https://github.com/TypeNetwork/variable-type-tools/issues/66 and https://github.com/TypeNetwork/variable-fonts-info-site/issues/106

**Comment by dberlow** [comment]
How would it be if we put these in the bottom bar, replacing the two circled links with:
‘’Github repo” and “bugs & requests”?
![76231B81-22F1-450C-B7DD-44B965E33FA6](https://user-images.githubusercontent.com/1956494/62410413-ff16c800-b5b2-11e9-8b30-2cb2963e49a2.jpeg)
