### ISSUE TITLE
Tell users this runs locally and no data is uploaded anywhere

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/videoproof#24]
People are often paranoid about testing their fonts on web apps that might suck up their fonts and store them on a server. 

This app does not do that, so we should tell people that.

**Comment by dberlow** [comment]
This okay?
[No add clause.pdf](https://github.com/TypeNetwork/videoproof/files/4186660/No.add.clause.pdf)

**Comment by davelab6** [comment]
Yes

**Comment by dberlow** [comment]
Hey Chris is this OK by you?

**Comment by ghost** [comment]
Yes! In fact I sat down to do it the other day and then got indecisive about exactly how to implement it :) will do.

**Comment by ghost** [comment]
I imitated the wording from wakamaifondue.com.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/587009/75919027-a857c200-5e11-11ea-9750-b460c5c8e1b5.png">

**Comment by dberlow** [comment]
Thanks!

> On Mar 4, 2020, at 3:14 PM, Chris Lewis <notifications@github.com> wrote:
> 

﻿
I imitated the wording from wakamaifondue.com.
