### ISSUE TITLE
Keyframe population of custom axes

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/videoproof#25]
When I drop a Tilt font from https://github.com/andyclymer/Tilt-Typeface, I don't get anything in the Keyframes section, so I can't use the app :( 

<img width="2004" alt="Screen Shot 2021-06-03 at 10 54 55" src="https://user-images.githubusercontent.com/261579/120666050-45ad0600-c45a-11eb-9ca7-e668ea3fa89b.png">

**Comment by dberlow** [comment]
I’m pretty sure you can play any of those axis that you want, But there is no algorithm that looks beyond the registered axes to create a set of keyframes.

On Jun 3, 2021, at 10:56 AM, Dave Crossland ***@***.***> wrote:

﻿
When I drop a Tilt font from https://github.com/andyclymer/Tilt-Typeface, I don't get anything in the Keyframes section, so I can't use the app :(

**Comment by graphicore** [comment]
![Screenshot from 2022-05-31 16-38-07](https://user-images.githubusercontent.com/393132/171200447-4a5ea365-b7f4-4fa7-9838-ff07ae3e39cd.png)

This is now possible. There are no "Keyframes", as the axis of tilt are not of the "registered" ones (`opsz`, `wdth`, `wght`), however under "But wait, there’s more" animations can be selected for the other axes.
