### ISSUE TITLE
Make font dropping (or fallback stack) more resilient

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/videoproof#27]
The font fallback stack in videoproof caused a problem for a reviewer of a private FB/G project this week. Possibly the dropped font was malformed, but there was not sufficient feedback from the app for the reviewer to understand the drop was not successful.

**Comment by graphicore** [comment]
It would be good to have the font or a similarly malformed font.

**Comment by davelab6** [comment]
Closed in favor of #32
