### ISSUE TITLE
Text is Inputting backwards

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#29]
I typed “TYPETOOLS”
![877A567A-5BB0-4AC9-8CE7-BAE8BA3E5E5F](https://user-images.githubusercontent.com/1956494/203642840-eb811615-470b-46cf-8f70-776f40bd243d.jpeg)

**Comment by graphicore** [comment]
I can reproduce this on iOS! On desktop browsers (Mac, Linux) this not the case. I can't test on Android and Windows as I have no such device. But I have this behavior on IPhone and IPad. I know where this happens, shouldn't be too hard to fix.

**Comment by dberlow** [comment]
I’m feeling exactly when this is as backwards as possible it can only be a mobile mac issue. Thanks for looking
