### ISSUE TITLE
Remove PHP requirement?

### ISSUE THREAD

**Issue by ghost** [TypeNetwork/videoproof#5]
Mirroring https://github.com/TypeNetwork/variable-type-tools/issues/68

PHP does even less here than it does there.

**Comment by graphicore** [comment]
Done as of 3db9e957eb12a680a408187fa8339238b81d6651 ff. There's still a [Legacy Version](https://videoproof.graphicore.de/legacy.php) with PHP dependency yet, for comparison purposes.
