### ISSUE TITLE
"Input", sizing

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#6]
Can we get something more like this for input sizing?
1. what we got, incl. default string
2. what I'd like, with same default string
3. what'd happen with on glyph
...next week sometime. 

[INPUT SIZING.pdf](https://github.com/TypeNetwork/videoproof/files/3464120/INPUT.SIZING.pdf)

Thanks.

**Comment by ghost** [comment]
Mostly working.

**Comment by dberlow** [comment]
Agreed. This'll be great when its working. 
There are a couple of repeatable bugs, one that crashes a browser.

A. fit input to page
Input: T, fills the page as required. 
check: Show Extended, adds the few versions of diacritic version of T, and scales to fit page, but adds a space between T and T-diacritics, not required.

Input: A,  fills the page as required. 
check: Show Extended, adds the many diacritic versions of A, does not fit to page, in adding a space between A and A-diacritics, two lines of text are created, scaled to fit the font size needed for the line length of the A-diacritics, I'm guessing. Should still fit to page.

B. Trying to change Input, from letter to another letter crashes the browser. 
Input: T fills the page as required. 
Highlight T in new text input box
Input A, freezes: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by ghost** [comment]
Fixed those.

**Comment by ghost** [comment]
Do you want it to account for wider variations in fitting the space? i.e. set to widest variation, fit the space, and then reset to default, to avoid unsightly wrapping when animating?

**Comment by dberlow** [comment]
I do not mind unsightly wrapping while our meeting. I would like portal depth set to the widest so the bottom bar is not jumping up and down?

On Aug 21, 2019, at 12:41 PM, Chris Lewis <notifications@github.com> wrote:

Do you want it to account for wider variations in fitting the space? i.e. set to widest variation, fit the space, and then reset to default, to avoid unsightly wrapping when animating?

**Comment by ghost** [comment]
Footer bar is now pinned to the bottom of the window.

**Comment by ghost** [comment]
Closing this for now. The line fitting is not perfect but usually sorts itself out if you twiddle the text a little bit.

**Comment by dberlow** [comment]
Thanks Chris, I'll get look soon!
