### ISSUE TITLE
Contextual spacing adjustment

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/videoproof#7]
When we, pad glyphs with letters, the resulting ‘words” can’t be broken at line ends.

We can drop one Padded letter, e.g. go from HHAHH to HAHH or HHAH, and we can lengthen the run as much as we need you breaking with large amounts of marginal raggedness, but intact “words” are the primary thing to see.

If some glyphs (-, ..., etc.) need special attention because composition by the browser or os wants to break somewhere, it can be stopped?

![4657F847-074C-436C-966B-ED1A6D8373EE](https://user-images.githubusercontent.com/1956494/62424409-21d0db80-b69c-11e9-9415-801915854afc.jpeg)

**Comment by dberlow** [comment]
Padding bug in contextual “punctuation’
![CE939956-AA4E-42AB-8604-052C0965E1C9](https://user-images.githubusercontent.com/1956494/62424500-1fbb4c80-b69d-11e9-9821-1144bc1f1adb.jpeg)

**Comment by dberlow** [comment]
Contextual/ascii, ends at figures, not including all ascii.
![DA6D025D-2F38-4FE7-968F-CEA4CDCEB840](https://user-images.githubusercontent.com/1956494/62424570-59408780-b69e-11e9-8c55-5f8c3af32c9f.jpeg)

**Comment by ghost** [comment]
Fixo!
