### ISSUE TITLE
Bookmark current settings in URL

### ISSUE THREAD

**Issue by ghost** [TypeNetwork/videoproof#9]
- [x] font/layout/glyph group
- [x] extended glyphs checkbox
- [x] animation keyframe
- [x] arbitrary paused main RAP animation
- [x] arbitrary paused parametric animation
- [x] colors
- [x] custom per-layout controls

**Comment by dberlow** [comment]
Sounds like it’s the right list unless were doing overlays? and then my name is stroke and a layer?
and by custom per layout controls you mean the CSS and JavaScript it does everything on the page?

**Comment by ghost** [comment]
This is just a to-do list for me to get “snapshot the current state” working.

**Comment by ghost** [comment]
This is mostly working. Whenever change controls or pause the animation, the URL will update itself to something that should reproduce the current state when reloaded.

I haven't quite gotten the parametric sub-animation state worked out yet.

**Comment by ghost** [comment]
I think this is all working! It's a bit hacky and occasionally fragile, but it does the job for getting a link to the entire page with the same state as before.

I imagine it would also be useful to have a simple "export" feature that would link to a bare-bones page that only shows the font sample at its frozen state. That would be very easy to do and less prone to failures, since all it would have to do is snapshot the font-variation-settings and apply those. Let me know if you do indeed want that.

**Comment by dberlow** [comment]
Is the definition of frozen state below, 
...the instances that the single page uses?
...the font styles/vf ranges the responsive pages use?  
...or it only displays in Alaska? 

On Aug 5, 2019, at 5:52 PM, Chris Lewis <notifications@github.com> wrote:

shows the font sample at its frozen state

**Comment by dberlow** [comment]
I’m not seeing a selection to do this url safe yet.

**Comment by ghost** [comment]
Do you mean like a nice/short URL? I can investigate @davelab6's urlhosted suggestion.

By "frozen" I mean, just emit a snapshot of the current proof, without any of the controls or UI: just a static page that would load quickly and show whatever glyph issues you wanted to communicate.

**Comment by dberlow** [comment]
Like save composition as url, is fine now. 

Save rap, save rap section, save keyframes, is not far beyond save keyframe?

On Aug 5, 2019, at 6:09 PM, Chris Lewis <notifications@github.com> wrote:

Do you mean like a nice/short URL? I can investigate @davelab6's urlhosted suggestion.

By "frozen" I mean, just emit a snapshot of the current proof, without any of the controls or UI: just a static page that would load quickly and show whatever glyph issues you wanted to communicate.

**Comment by ghost** [comment]
Oh I see. Right now, the url updates itself “live” as you make changes. I can replace this with a bookmark button that would actually show you the url and copy it to the clipboard.
